trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r SSO/requirements.txt
  displayName: 'Install dependencies'

- script: |
    cd SSO
    pytest --junitxml=junit/test-results.xml --html=reports/test-report.html
  displayName: 'Run test suite and generate HTML report'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'SSO/junit/test-results.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true
  displayName: 'Publish Test Results'
  condition: always()  # Ensures this task runs regardless of previous step outcomes

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'SSO/reports'  # Ensure this path is correct and contains the report
    artifactName: 'test-reports'
  displayName: 'Publish Test Reports Artifact'
  condition: always()  # Ensures this task runs regardless of previous step outcomes
