trigger:
  - main

pool:
  vmImage: 'macOS-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install pytest selenium
    displayName: 'Install dependencies'

  - script: |
      cd SSO
      pytest test_login.py --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'Run test suite'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'SSO/junit/test-results.xml'
