trigger:
- main  # or the branch you want to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10.14'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install pytest
    pip install -r SSO/requirements.txt
  displayName: 'Install dependencies'

- script: |
    sudo apt-get update
    sudo apt-get install -y chromium-browser
    sudo apt-get install -y chromium-chromedriver
  displayName: 'Install Chrome and ChromeDriver'

- script: |
    pytest test_login.py test_loginnegative.py test_logout.py
  workingDirectory: SSO
  displayName: 'Run tests with pytest'
