trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12.5'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r SSO/requirements.txt
    pip install webdriver-manager
  displayName: 'Install dependencies'
 
- script: |
    python -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"
  displayName: 'Install ChromeDriver using WebDriver Manager'
 
- script: |
    cd SSO
    pytest --junitxml=junit/test-results.xml
  displayName: 'Run test suite'
 
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit/test-results.xml'
