trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r SSO/requirements.txt
    pip install webdriver-manager
  displayName: 'Install dependencies'

- script: |
    python -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"
  displayName: 'Install ChromeDriver using WebDriver Manager'

- script: |
    cd SSO
    pytest --junitxml=junit/test-results.xml
  displayName: 'Run test suite'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'SSO/junit/test-results.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'SSO Test Results'
    publishRunAttachments: true  # Publishes the test results as artifacts

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $testResults = [xml](Get-Content "SSO/junit/test-results.xml")
      $total = $testResults.testsuites.testsuite.tests
      $failures = $testResults.testsuites.testsuite.failures
      $passed = $total - $failures
      $percentage = [math]::Round(($passed / $total) * 100, 2)
      Write-Host "##vso[task.setvariable variable=passPercentage;]$percentage"
      Write-Host "Test Passed Percentage: $percentage%"

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'SSO/junit'
    ArtifactName: 'TestResults'
    publishLocation: 'Container'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Test Passed Percentage: $(passPercentage)%"
  condition: succeededOrFailed()
