trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r SSO/requirements.txt
  displayName: 'Install dependencies'

- script: |
    cd SSO
    pytest test_login.py
    pytest test_loginnegative.py
    pytest test_logout.py
  displayName: 'Run test suite'
