trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r SSO/requirements.txt
  displayName: 'Install dependencies'

- script: |
    curl -sL https://github.com/allure-framework/allure2/releases/download/2.17.1/allure-2.17.1.zip -o allure.zip
    unzip allure.zip -d allure
    echo "##vso[task.prependpath]$(System.DefaultWorkingDirectory)/allure/allure-2.17.1/bin"
  displayName: 'Install Allure CLI'

- script: |
    cd SSO
    pytest --alluredir=allure-results
  displayName: 'Run test suite and generate Allure results'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'SSO/allure-results'
    artifactName: 'allure-results'
    publishLocation: 'pipeline'
  displayName: 'Publish Allure Results as Pipeline Artifact'

- script: |
    allure serve SSO/allure-results
  displayName: 'Generate and Serve Allure Report'
