trigger:
- main  # or the branch you want to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10.14'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install pytest
    pip install -r SSO/requirements.txt
    pip install webdriver_manager  # Ensure webdriver_manager is installed
  displayName: 'Install dependencies'

- script: |
    echo "[pytest]" > pytest.ini
    echo "markers =" >> pytest.ini
    echo "    order: mark test order" >> pytest.ini
  displayName: 'Register custom pytest marks'

- script: |
    pytest test_login.py test_loginnegative.py test_logout.py
  workingDirectory: SSO
  displayName: 'Run tests with pytest'
